channels:
    - conda-forge
name:
    synapse-net
dependencies:
    - bioimageio.core
    - kornia
    - magicgui
    - napari >=0.5.0,<0.6.0
    - nifty >=1.2.3
    - pip
    - pyqt
    - python-elf
    - pytorch
    - tensorboard
    - torch_em >=0.8.1
    - torchvision
    - trimesh
    - zarr <3
    - pip:
        - napari-skimage-regionprops
